#!/usr/bin/env bash

# TODO: add a function log to simplify logging

check_executable_exists() {
  command -v "$1" > /dev/null 2>&1
}

run_ssh_agent() {
  local log_filename=$1

  if check_executable_exists ssh-agent; then
    if [ -z "$SSH_AUTH_SOCK" ]
    then
      # Check for a currently running instance of the agent
      local RUNNING_AGENT=
      # RUNNING_AGENT="$(ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]')"
      if ! check_executable_exists pgrep; then
        echo -e "\n$(date +%Y-%m-%dT%H-%M-%S) - pgrep does not exist" >> "${log_filename}"
        return
      fi
      RUNNING_AGENT="$(pgrep ssh-agent)"
      if [ -z "$RUNNING_AGENT" ]; then
        ssh-agent -s > "${HOME}/.ssh/ssh-agent" 2>"${HOME}/.ssh/ssh-agent-error"

        # TODO: sed ${HOME}/.ssh/ssh-agent and get PID for a logging

        echo -e "\n$(date +%Y-%m-%dT%H-%M-%S) - ssh-agent is starting" >> "${log_filename}"
      else
        echo -e "\n$(date +%Y-%m-%dT%H-%M-%S) - ssh-agent is running(${RUNNING_AGENT})" >> "${log_filename}"
      fi
      eval "$(cat "${HOME}/.ssh/ssh-agent")"
    fi
  else
    echo -e "\n$(date +%Y-%m-%dT%H-%M-%S) - cannot find ssh-agent" >> "${log_filename}"
  fi
}

main() {
  local log_filename=/tmp/booldogrc.log
  
  while true
  do
    echo -e "\n$(date +%Y-%m-%dT%H-%M-%S) - booldogrc.sh is starting" >> "${log_filename}"

    run_ssh_agent "${log_filename}"

    if check_executable_exists ssh-add; then
      [ -f "${HOME}/.ssh/id_rsa" ] && ssh-add "${HOME}/.ssh/id_rsa"
    fi

    # [ -d "$HOME/sources/epiphan/trunk" ] && echo 'EXISTS2'
#     # export EPI_TRUNK="${HOME}/sources/epiphan/trunk"
    if check_executable_exists optirun; then
      alias opera='optirun opera'
      alias code='optirun code'
    fi

    if check_executable_exists "${HOME}/SQLiteStudio/sqlitestudio"; then
      alias sqlitestudio="${HOME}/SQLiteStudio/sqlitestudio"
    fi

    if check_executable_exists "${HOME}/GOGS/build_qml/qvideoclient"; then
      alias qvideoclient-debug='INTEGRA_S_VIDEO_LOG_WRITE_HOME_ALLOW=1 INTEGRA_S_VIDEO_LOG_PATH="'${HOME}'/GOGS/build_qml/log" MJSONDBGDISABLE="1" LD_PRELOAD='${HOME}'/GOGS/build_qml/libhookmem.so '${HOME}'/GOGS/build_qml/qvideoclient'
    fi

    if check_executable_exists "${HOME}/GOGS/build_server/video-server-7.0"; then
      alias videoserver-debug='INTEGRA_S_VIDEO_LOG_WRITE_HOME_ALLOW=1 INTEGRA_S_VIDEO_LOG_PATH="'${HOME}'/GOGS/build_server/log" MJSONDBGDISABLE="1" '${HOME}'/GOGS/build_server/video-server-7.0'
    fi

    if check_executable_exists "${HOME}/GOGS/build_qml/qvideoclient"; then
      alias qvideoclient-top='top -p `pgrep "qvideoclient"`'
    fi

#     # alias code='GTK_IM_MODULE=ibus code'    

    break
  done
}
main "$@"
